server {
  listen 80;
  server_name _;
  absolute_redirect off;

  types {
    application/pdf pdf;
    application/javascript js;
    image/svg+xml svg;
    text/css css;
    text/html html;
  }

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    try_files /index.html =404;
    add_header Cache-Control "no-store";
  }

  location = /index.html {
    try_files /index.html =404;
    add_header Cache-Control "no-store";
  }

  location / {
    try_files $uri =404;
    expires -1;
    add_header Cache-Control "no-store";
  }
}
